### PR TITLE
Delete transactions command

### PR DESCRIPTION
**Pull request by semaj**
I am a huge Haskell noob, but I know Bitcoin - so I'm exploring a real Haskell project that relates to Bitcoin. 

Please, criticize this.

### CODE REVIEW

**Comment by xenog** [comment]
Thanks semaj, we will review this and get back to you soon. :+1:

**Comment by plaprade** [comment]
Hi semaj,

Thanks for your pull request. I think that having a remove transaction command would indeed be very useful for the wallet. 

There are however a few questions to ask ourselves from a usage point of view. I think it makes a lot of sense to allow removing either offline transactions (because they have not been sent to the network yet) or pending transactions (0-confirmation transactions) because they may be stuck. Would it make sense to allow removing confirmed transactions? Once they are confirmed, if you delete them, you would have a wallet which is not aligned with the blockchain. Maybe there are acceptable use cases for removing confirmed transactions?

From an implementation point of view, when a transaction is imported into the wallet, a few things happen (in no particular order):
- A new transaction is created in `KeyRingTx` table
- If the transaction sends coins to your account, new coins are created in `KeyRingCoin`
- If the transaction spends any coins in your account, new entries for those coins are created in `KeyRingSpentCoin`
- If some addresses have been used (coins were received in them) in an account, then more addresses are generated in `KeyRingAddr` to maintain the address gap configured in the account.

So if we delete a transaction, we have to remove the new coins it created in `KeyRingCoin`, unspend coins that it was spending in `KeyRingSpentCoin` and then remove the transaction itself in `KeyRingTx`. I don't think we should remove any addresses once they have been generated.

Additionally, we also have to ask ourselves if we want to remove any child transactions of the transaction we are deleting. A child transaction would be a transaction that spends one or more coins from the transaction that we are deleting. If we remove a transaction because we want to replace it with a totally different one, then any child transactions should probably be deleted as well because they will never confirm. 

Let me know if you want to work on those improvements. Otherwise, I'm happy to send a patch to your pull request.

**Comment by semaj** [comment]
@plaprade 
You are totally right. I don't think it's particularly useful to delete confirmed transactions, but I think the same logic can be applied to 0-conf transactions. If you broadcast, then immediately delete, it could still be accepted by the network, which could cause some sync issues, no? This might be some naivety about the haskoin-wallet server on my part, though.

Offline transactions make perfect sense. I'll change it to affect offline transactions only for now, and await your response.

**Comment by xenog** [comment]
If you delete an unconfirmed transaction and then it shows up on the Bitcoin network, it will be re-imported.

**Comment by xenog** [comment]
There are some legitimate reasons to delete unconfirmed transactions, like when you send it with a very low fee and nodes refuse to forward it, such that it never reaches miners. I have experienced this in the past. If the transaction is broadcast, and it eventually gets into the blockchain, the worst thing that can happen if you delete it is an attempted double-spend that will be resolved when either transaction is confirmed.

**Comment by semaj** [comment]
@xenog @plaprade  https://github.com/haskoin/haskoin-wallet/blob/master/Network/Haskoin/Wallet/Types.hs#L119-L124 This looks like the signifier for the status of a transaction. TxOffline is self-explanatory, but do the others mean?

**Comment by plaprade** [comment]
The `TxConfidence` field tracks the confidence of a transaction on the network:
- `TxOffline` is a transaction that has not been broadcast to the network yet. It will usually be a partially signed multisignature transaction.
- `TxPending` is a transaction that was just broadcast to the network but did not receive a confirmation yet. It is pending confirmation. `TxPending` transactions usually make it to the blockchain but it is possible for them to stay in this state indefinitely. 
- `TxBuilding` is a transaction that made it into the main chain of the blockchain. The confidence of this transaction is building up. A `TxBuilding` transaction will have 1 or more confirmations. 
- `TxDead` is a transaction that is in conflict with another transaction (double spending the same coins) and is not currently in the main chain of the blockchain.  A `TxDead` transaction can be in conflict with a `TxPending` transaction (the first transaction that was imported will be `TxPending` and the second one will be `TxDead`). The first transaction that makes it into a block will be marked as `TxBuilding` and the other one `TxDead`. It is always possible for a `TxDead` transaction to be revived and go into `TxBuilding` status if a reorg happens where the `TxDead` transaction is part of the main chain again. 

Hope this clarifies that field a bit.

**Comment by plaprade** [comment]
To answer the question about deleting pending transactions, I'm not exactly sure what will happen. I know that bitcoin core keeps an inventory of known items for a peer (which would track which txs a peer knows about) but I'm not sure under which circumstances this inventory is updated. I would imagine that the purpose of the inventory is to avoid sending things to a peer that he already knows about. However, if we delete a transaction, there is a possibility that we might not get it back from the peer if the peer thinks we already know about it. I would need to look into this a bit further.

**Comment by semaj** [comment]
hey @xenog or @plaprade can one of you pull this down, build, and try to 'rmtx' a confirmed transaction? I'm seeing `hw: when expecting a Bool, encountered Array instead` and not sure why.

**Comment by plaprade** [comment]
Hi semaj, I pulled your code and it worked fine (it showed the correct messages), I could not reproduce your issue:

With a pending transaction:
```
hw rmtx public 5c59fd8e946e6c7c7e7d0ce6ca75e51d7e1e259577d91334d35239ac3f0204e7
Transaction deleted.
```
And with a confirmed transaction:
```
hw rmtx public 3a160d9654c01b95c605fc49be1bbfcfc8fd6549428c74dd4662db46734fc5ff
hw: Tx must be Offline, Pending, or Dead.
```
Are you installing haskoin-wallet with stack (`stack install`)? Otherwise, which versions of GHC and Data.Aeson are you using?

**Comment by semaj** [comment]
@plaprade I did use `stack install` and GHC version is 7.10.1. How do I check the version of aeson? Also, I installed GHC with homebrew & stack while having Haskell Platform already on my computer, can that cause issues?

**Comment by xenog** [comment]
It is strange that you used GHC 7.10 and Stack to install this package. The Stack definition for this package uses GHC 7.8. If you installed the package with `stack install` successfully, then it compiled with GHC 7.8 instead of GHC 7.10. Stack is capable of obtaining GHC on its own, and it can have multiple versions of the compiler available simultaneously.

**Comment by plaprade** [comment]
Which version of stack are you using (`stack --version`)? You can get more information on what stack is doing during installation with `stack install -v`. You will see which ghc version is being used to install haskoin-wallet. It should be using version 7.8.4 (stack looks at the `stack.yaml` file in the haskoin-wallet project and will use the given resolver which is lts-2.15). The definition for lts-2.15 is here: 

https://www.stackage.org/lts-2.15 

Can you test the following for us? In the haskoin-wallet repository, load up ghci with `stack ghci`. Once in ghci, execute the following command:

```
Data.Aeson.eitherDecode $ Data.Aeson.encode $ ResponseValid (Just (Data.Aeson.toJSON True)) :: Either String (WalletResponse Bool)
```
Let me know if it works (it should return the following:)

```
Right (ResponseValid {responseResult = Just True})
```

**Comment by semaj** [comment]
Running `stack ghci` gives me:

~~~
Configuring GHCi with the following packages: haskoin-wallet, haskoin, haskoin-node
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package HUnit
    (use -v for more information)
~~~

**Comment by plaprade** [comment]
That happens to me when the project isn't built. Try running `stack setup` followed by `stack build` and then `stack ghci`.

**Comment by xenog** [comment]
Hey semaj,

If you would like some real-time help, you can go to #haskell on [Freenode](freenode.net).

**Comment by xenog** [comment]
In case you did not see the correction for the previous message: I meant #haskoin, not #haskell.

**Comment by semaj** [comment]
@plaprade I ran `stack install HUnit` and a number of other test packages, and got `stack ghci` working. I ran `stack clean`, then `stack install`, and things seem to be good now. Thanks! How does the PR look?

@xenog I have popped in there a few times, no one ever responds :P I'm jamesfordummies on Freenode.

**Comment by semaj** [comment]
Hey @xenog just patched those few things up. Let me know if there's anything else.

**Comment by xenog** [comment]
You also need to change `config/help` to add usage documentation for the new option.

**Comment by xenog** [comment]
Should be done in the new repository.

**Pull request closed without merging**
